[package]
name = "my-clipboard"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "my_clipboard_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2.0.0", features = ["protocol-asset", "tray-icon"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clipboard-rs = "0.2.1"
base64 = "0.22.1"
image = { version = "0.25.1", default-features = false, features = ["png", "jpeg", "gif", "bmp", "ico", "tiff", "webp"] }
aes-gcm = "0.10.3"
argon2 = "0.5.3"
rand = "0.8.5"
zeroize = "1.8.2"
tauri-plugin-global-shortcut = "2.0.0"
tauri-plugin-autostart = "2.0.0"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-global-shortcut = "2"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = "symbols"
debug = 0
panic = "abort"
