async (page) => {
  const results = [];
  const check = (name, ok) => { results.push({ name, pass: !!ok }); if (!ok) throw new Error(name); };
  const invoke = (command, args) => page.evaluate(({ command, args }) => window.__TAURI_INTERNALS__.invoke(command, args), { command, args });
  const nav = name => page.locator('.ref-primary-nav').getByRole('button', { name, exact: true }).click();
  const waitRecord = text => page.waitForFunction(async text => (await window.__TAURI_INTERNALS__.invoke('clipboard_store_load')).records.some(r => r.content === text), text);
  page.on('pageerror', error => results.push({ name: 'runtime', pass: false, error: error.message }));
  try {
    check('isolated QA identifier', await invoke('plugin:app|identifier') === 'com.lenovo.my-clipboard.qa-phase2');
    check('native bridge and production data mode', await page.evaluate(() => !!window.__TAURI_INTERNALS__ && !document.querySelector('.reference-mode')));
    check('native CSS viewport 1586x992', await page.evaluate(() => innerWidth === 1586 && innerHeight === 992));
    await page.evaluate(async () => {
      if (!localStorage.getItem('phase2-original-clipboard')) localStorage.setItem('phase2-original-clipboard', JSON.stringify(await window.__TAURI_INTERNALS__.invoke('get_clipboard_data')));
      const store = await window.__TAURI_INTERNALS__.invoke('clipboard_store_load');
      store.records = [];
      store.preferences.captureEnabled = false;
      await window.__TAURI_INTERNALS__.invoke('clipboard_store_replace', { store });
    });
    await page.reload();
    await page.getByText('No text clips yet. Copy text to get started.').waitFor({ timeout: 5000 });
    check('empty history state', true);
    await nav('Settings');
    await page.getByRole('button', { name: 'Toggle clipboard capture', exact: true }).click();
    await page.waitForFunction(async () => (await window.__TAURI_INTERNALS__.invoke('clipboard_store_load')).preferences.captureEnabled);
    check('capture saved on', (await invoke('clipboard_store_load')).preferences.captureEnabled);
    await invoke('set_clipboard_text', { text: 'PHASE2-QA live text one' });
    await waitRecord('PHASE2-QA live text one');
    await nav('Characters');
    await page.locator('.clip-row').filter({ hasText: 'PHASE2-QA live text one' }).click();
    check('live clipboard text captured and selected', await page.locator('.clip-content').innerText() === 'PHASE2-QA live text one');
    await page.getByRole('button', { name: 'Copy all', exact: true }).click();
    check('UI copy text reaches Windows clipboard', (await invoke('get_clipboard_data'))[1] === 'PHASE2-QA live text one');
    await page.getByRole('button', { name: 'Pin clip', exact: true }).click();
    await page.waitForFunction(async () => (await window.__TAURI_INTERNALS__.invoke('clipboard_store_load')).records.some(r => r.content === 'PHASE2-QA live text one' && r.isPinned));
    check('pin persisted', true);
    await page.locator('.ref-search input').fill('not-a-matching-clip');
    check('search empty result', await page.locator('.clip-row').count() === 0);
    await page.locator('.ref-search input').fill('');
    await invoke('set_clipboard_text', { text: 'PHASE2-QA live text two' });
    await waitRecord('PHASE2-QA live text two');
    await page.locator('.clip-row').filter({ hasText: 'PHASE2-QA live text two' }).click();
    await page.getByRole('button', { name: 'Delete clip', exact: true }).click();
    await page.waitForFunction(async () => !(await window.__TAURI_INTERNALS__.invoke('clipboard_store_load')).records.some(r => r.content === 'PHASE2-QA live text two'));
    check('delete text persisted', true);
    await invoke('set_clipboard_image_from_path', { path: 'E:\\clipboard\\my-clipboard\\static\\reference-assets\\images\\selected.png' });
    await page.waitForFunction(async () => (await window.__TAURI_INTERNALS__.invoke('clipboard_store_load')).records.some(r => r.type === 'image'));
    await nav('Images');
    await page.locator('.image-grid img').first().waitFor();
    await page.waitForFunction(() => [...document.querySelectorAll('.image-grid img')].some(image => image.naturalWidth > 0));
    check('native image capture and thumbnail decode', true);
    await page.getByRole('button', { name: 'Copy image', exact: true }).click();
    check('UI copy image reaches Windows clipboard', (await invoke('get_clipboard_data'))[0] === 'image');
    await nav('Settings');
    await page.getByRole('button', { name: 'Toggle clipboard capture', exact: true }).click();
    await invoke('set_clipboard_text', { text: 'PHASE2-QA paused text' });
    await page.waitForTimeout(2500);
    check('capture pause stops new records', !(await invoke('clipboard_store_load')).records.some(r => r.content === 'PHASE2-QA paused text'));
    await page.locator('.native-settings summary').click();
    await page.locator('.native-setting input[type=number]').fill('25');
    await page.getByRole('button', { name: 'Save retention', exact: true }).click();
    await page.waitForFunction(async () => (await window.__TAURI_INTERNALS__.invoke('clipboard_store_load')).preferences.retentionHours === 25);
    check('retention configuration saved', true);
    const startupBefore = await invoke('autostart_status');
    await page.getByRole('button', { name: 'Toggle launch at startup' }).click();
    check('autostart toggled natively', await invoke('autostart_status') !== startupBefore);
    await page.getByRole('button', { name: 'Toggle launch at startup' }).click();
    check('autostart restored', await invoke('autostart_status') === startupBefore);
    await page.locator('.shortcut-control').click();
    await page.locator('.shortcut-editor input').press('Alt+V');
    await page.getByRole('button', { name: 'Apply', exact: true }).click();
    check('global shortcut saved natively', (await invoke('shortcut_status')).shortcut === 'Alt+V');
    await nav('Characters');
    await page.screenshot({ path: 'design-qa/final/native-recent.png', type: 'png', scale: 'css' });
  } catch (error) { results.push({ name: 'stopped', pass: false, error: error.message }); }
  await page.evaluate(results => localStorage.setItem('phase2-test-results', JSON.stringify(results)), results);
  return results;
}
